import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fetchDocument, wait } from './fetch';
import { normalizeOpenApi, parseOpenApi } from './openapi';
import { renderFeatureDocument, renderIndex, renderRegistry } from './render';
import {
	inspectDocumentationSource,
	inspectPageDataSource,
	mergeSupplemental,
	pageDataUrlFor
} from './source';
import type { NormalizedOpenApi, SourceInspection, SupplementalDocument } from './types';

type Options = {
	sourcesPath: string;
	outputDirectory: string;
	cacheDirectory: string;
	check: boolean;
};

type UnresolvedSource = {
	url: string;
	reason: string;
	supplemental: SupplementalDocument | null;
};

function parseArguments(): Options {
	const argumentsList = process.argv.slice(2);
	const valueAfter = (flag: string) => {
		const index = argumentsList.indexOf(flag);
		return index >= 0 ? argumentsList[index + 1] : undefined;
	};
	const root = process.cwd();
	return {
		sourcesPath: path.resolve(
			root,
			valueAfter('--sources') ?? 'tools/youcam-docs-sync/sources.txt'
		),
		outputDirectory: path.resolve(root, valueAfter('--out') ?? 'docs/youcam-api'),
		cacheDirectory: path.resolve(root, valueAfter('--cache') ?? 'tools/youcam-docs-sync/.cache'),
		check: argumentsList.includes('--check')
	};
}

async function readSources(filePath: string) {
	const text = await readFile(filePath, 'utf8');
	const urls = text
		.split(/\r?\n/)
		.map((line) => line.trim())
		.filter((line) => line && !line.startsWith('#'));
	const unique = [...new Set(urls)];
	for (const url of unique) {
		try {
			const parsed = new URL(url);
			if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error();
		} catch {
			throw new Error(`Invalid source URL in ${filePath}: ${url}`);
		}
	}
	if (!unique.length) throw new Error(`No source URLs found in ${filePath}`);
	return unique;
}

function canonicalUrl(url: string) {
	const parsed = new URL(url);
	parsed.hash = '';
	return parsed.toString();
}

function uniqueFeatureId(feature: NormalizedOpenApi, existing: NormalizedOpenApi[]) {
	if (!existing.some((candidate) => candidate.id === feature.id)) return feature.id;
	const versionSuffix = feature.version
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-|-$/g, '');
	const candidate = `${feature.id}${versionSuffix ? `-${versionSuffix}` : '-alternate'}`;
	if (!existing.some((item) => item.id === candidate)) return candidate;
	return `${candidate}-${existing.filter((item) => item.id.startsWith(candidate)).length + 1}`;
}

function normalizedContent(value: string) {
	return value
		.toLowerCase()
		.replace(/!\[[^\]]*]\([^)]*\)/g, '')
		.replace(/[^a-z0-9]+/g, '');
}

function removeDuplicateSupplemental(
	feature: NormalizedOpenApi,
	documents: SupplementalDocument[]
) {
	const description = normalizedContent(feature.description);
	return documents.filter((document) => {
		const supplemental = normalizedContent(document.markdown);
		if (!supplemental) return false;
		const sample = supplemental.slice(0, Math.min(400, supplemental.length));
		return !description.includes(sample);
	});
}

function renderUnresolved(sources: UnresolvedSource[]) {
	return [
		'<!-- Generated by tools/youcam-docs-sync. Do not edit this file directly. -->',
		'',
		'# Unresolved YouCam documentation sources',
		'',
		'These sources did not expose a valid OpenAPI description. They remain listed here so they are not silently dropped.',
		'',
		...sources.flatMap((source) => [
			`## ${source.supplemental?.title || source.url}`,
			'',
			`- **Source:** [${source.url}](${source.url})`,
			`- **Reason:** ${source.reason}`,
			source.supplemental?.markdown ? `\n${source.supplemental.markdown}` : '',
			''
		])
	]
		.filter(Boolean)
		.join('\n');
}

async function readExisting(filePath: string) {
	try {
		return await readFile(filePath, 'utf8');
	} catch {
		return null;
	}
}

async function synchronizeFiles(
	outputDirectory: string,
	files: Map<string, string>,
	check: boolean
) {
	const manifestPath = path.join(outputDirectory, '.generated-files.json');
	const previousManifestText = await readExisting(manifestPath);
	const previousFiles: string[] = previousManifestText
		? ((JSON.parse(previousManifestText) as { files?: string[] }).files ?? [])
		: [];
	const nextFiles = [...files.keys()].sort();
	const changed: string[] = [];

	for (const [name, content] of files) {
		const existing = await readExisting(path.join(outputDirectory, name));
		if (existing !== content) changed.push(name);
	}
	for (const stale of previousFiles.filter((name) => !files.has(name))) changed.push(stale);

	if (check) return changed;

	await mkdir(outputDirectory, { recursive: true });
	for (const stale of previousFiles.filter((name) => !files.has(name))) {
		await rm(path.join(outputDirectory, stale), { force: true });
	}
	for (const [name, content] of files) {
		await writeFile(path.join(outputDirectory, name), content);
	}
	await writeFile(manifestPath, `${JSON.stringify({ files: nextFiles }, null, 2)}\n`);
	return changed;
}

async function main() {
	const options = parseArguments();
	const sourceUrls = await readSources(options.sourcesPath);
	const openApiDocuments = new Map<string, { body: string; sourceUrl: string }>();
	const supplementalByOpenApi = new Map<string, SupplementalDocument[]>();
	const unresolved: UnresolvedSource[] = [];
	const errors: string[] = [];

	async function collectInspection(inspection: SourceInspection, originalUrl: string) {
		const inspections = [inspection];
		const visitedPageData = new Set<string>();
		const pendingPageData = [...inspection.pageDataUrls];

		while (pendingPageData.length) {
			const pageDataUrl = pendingPageData.shift();
			if (!pageDataUrl) continue;
			const key = canonicalUrl(pageDataUrl);
			if (visitedPageData.has(key)) continue;
			visitedPageData.add(key);
			try {
				const pageDataDocument = await fetchDocument(pageDataUrl, options.cacheDirectory);
				const pageDataInspection = inspectPageDataSource(pageDataDocument);
				if (!pageDataInspection) continue;
				inspections.push(pageDataInspection);
				pendingPageData.push(...pageDataInspection.pageDataUrls);
			} catch (error) {
				errors.push(error instanceof Error ? error.message : String(error));
			}
		}

		const openApiUrls = [...new Set(inspections.flatMap((candidate) => candidate.openApiUrls))];
		const supplemental = inspections.reduce<SupplementalDocument[]>(
			(documents, candidate) => mergeSupplemental(documents, candidate.supplemental),
			[]
		);
		if (!openApiUrls.length) {
			unresolved.push({
				url: originalUrl,
				reason: 'No OpenAPI link was discovered on the page or in its page-data.',
				supplemental: supplemental[0] ?? null
			});
			return;
		}

		for (const discoveredUrl of openApiUrls) {
			const key = canonicalUrl(discoveredUrl);
			supplementalByOpenApi.set(
				key,
				supplemental.reduce(
					(documents, document) => mergeSupplemental(documents, document),
					supplementalByOpenApi.get(key) ?? []
				)
			);
			if (openApiDocuments.has(key)) continue;
			try {
				await wait(150);
				const discovered = await fetchDocument(discoveredUrl, options.cacheDirectory);
				if (!parseOpenApi(discovered.body)) {
					unresolved.push({
						url: discoveredUrl,
						reason: 'The discovered document is not valid OpenAPI.',
						supplemental: supplemental[0] ?? null
					});
					continue;
				}
				openApiDocuments.set(key, {
					body: discovered.body,
					sourceUrl: discovered.url
				});
			} catch (error) {
				errors.push(error instanceof Error ? error.message : String(error));
			}
		}
	}

	for (const [index, sourceUrl] of sourceUrls.entries()) {
		try {
			const derivedPageDataUrl = pageDataUrlFor(sourceUrl);
			if (derivedPageDataUrl) {
				const pageDataDocument = await fetchDocument(derivedPageDataUrl, options.cacheDirectory);
				const pageDataInspection = inspectPageDataSource(pageDataDocument);
				if (pageDataInspection) {
					await collectInspection(pageDataInspection, sourceUrl);
					if (index < sourceUrls.length - 1) await wait(150);
					continue;
				}
			}

			const document = await fetchDocument(sourceUrl, options.cacheDirectory);
			if (parseOpenApi(document.body)) {
				openApiDocuments.set(canonicalUrl(document.url), {
					body: document.body,
					sourceUrl: document.url
				});
			} else {
				await collectInspection(inspectDocumentationSource(document), sourceUrl);
			}
		} catch (error) {
			errors.push(error instanceof Error ? error.message : String(error));
		}
		if (index < sourceUrls.length - 1) await wait(150);
	}

	const features: NormalizedOpenApi[] = [];
	for (const [key, document] of openApiDocuments) {
		const parsed = parseOpenApi(document.body);
		if (!parsed) continue;
		const feature = normalizeOpenApi(parsed, document.sourceUrl);
		feature.id = uniqueFeatureId(feature, features);
		feature.supplemental = removeDuplicateSupplemental(
			feature,
			supplementalByOpenApi.get(key) ?? []
		);
		features.push(feature);
	}
	features.sort((a, b) => a.title.localeCompare(b.title) || a.version.localeCompare(b.version));

	if (!features.length) {
		throw new Error(
			`No valid OpenAPI descriptions were found.${errors.length ? `\n${errors.join('\n')}` : ''}`
		);
	}

	const generatedFiles = new Map<string, string>();
	generatedFiles.set('README.md', renderIndex(features));
	generatedFiles.set('registry.json', renderRegistry(features));
	for (const feature of features) {
		generatedFiles.set(`${feature.id}.md`, renderFeatureDocument(feature));
	}
	if (unresolved.length) generatedFiles.set('UNRESOLVED.md', renderUnresolved(unresolved));

	const changed = await synchronizeFiles(options.outputDirectory, generatedFiles, options.check);

	console.log(
		`${options.check ? 'Checked' : 'Synchronized'} ${features.length} features from ${sourceUrls.length} sources.`
	);
	if (changed.length) {
		console.log(`${options.check ? 'Outdated' : 'Updated'}: ${changed.sort().join(', ')}`);
	}
	if (unresolved.length) console.warn(`Unresolved sources: ${unresolved.length}`);
	if (errors.length) {
		console.error(errors.join('\n'));
		process.exitCode = 1;
	}
	if (options.check && changed.length) process.exitCode = 1;
}

main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exitCode = 1;
});
