import type {
	Endpoint,
	NormalizedOpenApi,
	SchemaField,
	SchemaSummary,
	SupplementalDocument
} from './types';

const GENERATED_NOTICE =
	'<!-- Generated by tools/youcam-docs-sync. Do not edit this file directly. -->';

function escapeTable(value: string) {
	return value.replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim() || '—';
}

function flattenFields(fields: SchemaField[], prefix = ''): SchemaField[] {
	return fields.flatMap((field) => {
		const name = prefix ? `${prefix}.${field.name}` : field.name;
		const current = { ...field, name, fields: [] };
		return [current, ...flattenFields(field.fields, name)];
	});
}

function renderSchema(schema: SchemaSummary | null) {
	if (!schema) return '';
	const fields = flattenFields(schema.fields);
	const lines = [`**Schema:** \`${schema.type}\``];
	if (schema.description) lines.push('', schema.description);
	if (fields.length) {
		lines.push(
			'',
			'| Field | Type | Required | Description |',
			'| --- | --- | --- | --- |',
			...fields.map(
				(field) =>
					`| \`${escapeTable(field.name)}\` | \`${escapeTable(field.type)}\` | ${field.required ? 'Yes' : 'No'} | ${escapeTable(field.description)} |`
			)
		);
	}
	return lines.join('\n');
}

function renderParameters(endpoint: Endpoint) {
	if (!endpoint.parameters.length) return '';
	return [
		'#### Parameters',
		'',
		'| Name | In | Type | Required | Description |',
		'| --- | --- | --- | --- | --- |',
		...endpoint.parameters.map(
			(parameter) =>
				`| \`${escapeTable(parameter.name)}\` | ${escapeTable(parameter.location)} | \`${escapeTable(parameter.type)}\` | ${parameter.required ? 'Yes' : 'No'} | ${escapeTable(parameter.description)} |`
		),
		''
	].join('\n');
}

function renderRequestBodies(endpoint: Endpoint) {
	if (!endpoint.requestBodies.length) return '';
	return [
		'#### Request body',
		'',
		...endpoint.requestBodies.flatMap((body) => [
			`**${body.contentType}**${body.required ? ' · required' : ''}`,
			'',
			renderSchema(body.schema),
			''
		])
	].join('\n');
}

function renderResponses(endpoint: Endpoint) {
	if (!endpoint.responses.length) return '';
	return [
		'#### Responses',
		'',
		...endpoint.responses.flatMap((response) => [
			`**${response.status}** — ${response.description || 'No description provided.'}`,
			response.contentTypes.length
				? `Content types: ${response.contentTypes.map((type) => `\`${type}\``).join(', ')}`
				: '',
			response.schema ? renderSchema(response.schema) : '',
			''
		])
	]
		.flat()
		.filter((line) => line !== '')
		.join('\n\n');
}

function renderEndpoint(endpoint: Endpoint) {
	const heading = `### \`${endpoint.method}\` \`${endpoint.path}\``;
	const metadata = [
		endpoint.tags.length ? `**Tags:** ${endpoint.tags.join(', ')}` : '',
		endpoint.security.length ? `**Authentication:** ${endpoint.security.join(', ')}` : ''
	].filter(Boolean);
	return [
		heading,
		'',
		`**${endpoint.summary}**`,
		endpoint.description ? `\n${endpoint.description}` : '',
		metadata.length ? `\n${metadata.join('\n\n')}` : '',
		'',
		renderParameters(endpoint),
		renderRequestBodies(endpoint),
		renderResponses(endpoint)
	]
		.filter(Boolean)
		.join('\n');
}

function demoteHeadings(markdown: string) {
	return markdown.replace(
		/^(#{1,4})\s+/gm,
		(_, hashes: string) => `${'#'.repeat(hashes.length + 2)} `
	);
}

function demoteOverviewHeadings(markdown: string) {
	return markdown.replace(
		/^(#{1,5})\s+/gm,
		(_, hashes: string) => `${'#'.repeat(hashes.length + 1)} `
	);
}

function renderSupplemental(document: SupplementalDocument) {
	return [
		`### ${document.title}`,
		'',
		`Source: [${document.sourceUrl}](${document.sourceUrl})`,
		'',
		demoteHeadings(document.markdown)
	].join('\n');
}

export function renderFeatureDocument(feature: NormalizedOpenApi) {
	const authentication = feature.securitySchemes.length
		? [
				'## Authentication',
				'',
				'| Name | Type | Scheme / Location | Description |',
				'| --- | --- | --- | --- |',
				...feature.securitySchemes.map(
					(scheme) =>
						`| ${escapeTable(scheme.name)} | ${escapeTable(scheme.type)} | ${escapeTable(scheme.scheme)} | ${escapeTable(scheme.description)} |`
				),
				''
			]
		: [];

	const supplemental = feature.supplemental.length
		? [
				'## Supplemental notes',
				'',
				...feature.supplemental.flatMap((document) => [renderSupplemental(document), ''])
			]
		: [];

	return [
		GENERATED_NOTICE,
		'',
		`# ${feature.title}`,
		'',
		demoteOverviewHeadings(feature.description) ||
			'No feature overview was provided in the OpenAPI description.',
		'',
		'## Reference',
		'',
		`- **API version:** ${feature.version || 'Not specified'}`,
		`- **OpenAPI version:** ${feature.openapiVersion || 'Not specified'}`,
		`- **Source:** [OpenAPI description](${feature.sourceUrl})`,
		feature.servers.length
			? `- **Servers:** ${feature.servers.map((server) => `\`${server}\``).join(', ')}`
			: '- **Servers:** Not specified',
		'',
		...authentication,
		'## Endpoints',
		'',
		...feature.endpoints.flatMap((endpoint) => [renderEndpoint(endpoint), '']),
		...supplemental
	]
		.join('\n')
		.replace(/\n{4,}/g, '\n\n\n')
		.trim()
		.concat('\n');
}

export function renderIndex(features: NormalizedOpenApi[]) {
	return [
		GENERATED_NOTICE,
		'',
		'# YouCam API Reference',
		'',
		'Human-readable API documentation synchronized from the official OpenAPI descriptions listed in `tools/youcam-docs-sync/sources.txt`.',
		'',
		'## Features',
		'',
		'| Feature | Version | Endpoints | Source |',
		'| --- | --- | ---: | --- |',
		...features.map(
			(feature) =>
				`| [${escapeTable(feature.title)}](./${feature.id}.md) | ${escapeTable(feature.version)} | ${feature.endpoints.length} | [OpenAPI](${feature.sourceUrl}) |`
		),
		'',
		'## Update',
		'',
		'```bash',
		'pnpm sync:youcam-docs',
		'```',
		'',
		'Generated files are deterministic. Use `pnpm sync:youcam-docs:check` in CI to detect documentation drift.'
	].join('\n');
}

export function renderRegistry(features: NormalizedOpenApi[]) {
	return `${JSON.stringify(
		{
			schemaVersion: 1,
			features
		},
		null,
		2
	)}\n`;
}
